### ISSUE TITLE
why i can use ssh to access the docker container 'pgyvpn' ?

### ISSUE THREAD

**Issue by xinyuecai2016** [sukeyisme/Dockerfiles#1]
I cannot ssh to it, even if i setup the sshd service , i am puzzled.
what's more,  pgyvpn in the docker is useless in docker. Do you have some amazing usages, i am eager to known about it. ths a lot~

**Comment by sukeyisme** [comment]
能说具体点吗

**Comment by sptj** [comment]
哈哈哈，能啊。就是我好像不能ssh上这个docker container实例。
刚才试了一下重装openssh-server才可用了
你说你不用这个镜像了，那么你用哪个镜像呢？或者你使用哪款可以公网IP就能使用的vpn软件呢？
~(^,^)~

**Comment by sukeyisme** [comment]
我没有公网ip，就用的n2n直连
